# Generated by Django 4.1.4 on 2024-03-01 23:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Balcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('prix', models.IntegerField(null=True)),
                ('balcon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.balcon')),
                ('chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactezNous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Douche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('arrondissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.arrondissement')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images_terrain')),
                ('croquis', models.FileField(upload_to='pdf_terrain')),
                ('prix', models.IntegerField(null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('arrondissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.arrondissement')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.commune')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.departement')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.operation')),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quartier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.quartier')),
            ],
            options={
                'verbose_name_plural': 'Terrains',
            },
        ),
        migrations.CreateModel(
            name='Porte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portes',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('croquis', models.FileField(upload_to='pdf_terrain')),
                ('prix', models.IntegerField(null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('prix', models.IntegerField(null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('statut', models.BooleanField(blank=True, default=False)),
                ('arrondissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.arrondissement')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.commune')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.departement')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.operation')),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quartier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.quartier')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.types')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images_plan')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesImmeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images_immeuble')),
                ('immeuble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.immeuble')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images_annomces')),
                ('annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images_chambre')),
                ('chambres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.chambres')),
            ],
            options={
                'verbose_name_plural': 'Chambres',
            },
        ),
        migrations.CreateModel(
            name='Divertissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images_divertissement')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('quartier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.quartier')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.departement'),
        ),
        migrations.AddField(
            model_name='chambres',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.cuisine'),
        ),
        migrations.AddField(
            model_name='chambres',
            name='douche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.douche'),
        ),
        migrations.AddField(
            model_name='chambres',
            name='immeuble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.immeuble'),
        ),
        migrations.AddField(
            model_name='chambres',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chambres',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.salon'),
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.commune'),
        ),
    ]
