# Generated by Django 4.1.4 on 2024-03-03 16:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0004_divertissement_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
