# Generated by Django 4.1.4 on 2024-04-15 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immobilier', '0008_rename_images_rejoindrecontact_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassadeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambassadeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chambres',
            name='ambassadeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.ambassadeur'),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='ambassadeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.ambassadeur'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='ambassadeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.ambassadeur'),
        ),
    ]
