# Generated by Django 4.1.4 on 2024-04-17 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immobilier', '0009_ambassadeur_chambres_ambassadeur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambres',
            name='ambassadeur',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='ambassadeur',
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='ambassadeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambassadeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ambassadeur',
        ),
    ]
