# Generated by Django 4.1.4 on 2024-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0010_remove_chambres_ambassadeur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommanderImmeubilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('quantite', models.IntegerField(null=True)),
            ],
        ),
    ]
