# Generated by Django 4.1.4 on 2024-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0011_commanderimmeubilier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanderimmeubilier',
            name='numero_chambre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
