# Generated by Django 4.1.4 on 2024-04-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0012_commanderimmeubilier_numero_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commanderimmeubilier',
            name='numero_chambre',
        ),
        migrations.RemoveField(
            model_name='commanderimmeubilier',
            name='quantite',
        ),
    ]
