# Generated by Django 4.1.4 on 2024-04-02 17:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_revuspresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.categoriepresse')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentairePresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.categoriepresse')),
            ],
        ),
    ]
