# Generated by Django 4.1.4 on 2024-04-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_commanderedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanderedition',
            name='adresse',
            field=models.CharField(max_length=100),
        ),
    ]
