# Generated by Django 4.1.4 on 2024-04-15 19:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteuruser',
            name='is_agent_immobiliere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auteuruser',
            name='is_ambassadeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auteuruser',
            name='bibliographie',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auteuruser',
            name='biographie',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
