# Generated by Django 4.1.4 on 2024-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editioncontact',
            name='soumettre',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editioncontact',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
